# Generated by Django 3.0.6 on 2020-12-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0004_auto_20201214_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentComment',
        ),
    ]
